<script>
        $(document).ready(function(){
        $(".owl-carousel").owlCarousel({
            items:1,
            nav:true,
            loop:true,
            autoplay:true,
            autoplayHoverPause:true,
        });
        });
</script>